### ISSUE TITLE
Code in AQSysCurve does not return rawdt

### ISSUE THREAD

**Issue by spkaluzny** [eqipehub/LLSR#2]
The code in AQSysCurve computes a curve:

    # generate curve using selected Fn function and store data in rawdt
    rawdt <- curve(
      Fn(param, x), col = col, add = mpl,
      xlim = c(0, xmax), xlab = xlbl, ylab = ylbl, lwd = clwd
    )

The code then names the components of rawdt and converts it to a data.frame. Then follow up with the code:

    # make data available to user
    invisible(rawdt)

as if to make the data.frame invisibly available to the user. But the user never gets access to rawdt since the invisible(rawdt) is not the last line in the function, rather the function returns NULL or the value of dev.cur() if save=TRUE.

**Comment by diegofcoelho** [comment]
fixed on 0.0.2.4
