### ISSUE TITLE
Code in  AQSys.plot does not return rawdt 

### ISSUE THREAD

**Issue by spkaluzny** [eqipehub/LLSR#3]
The code in AQSys.plot computes a curve:

    # add curve generated using regression parameters
    rawdt <- curve(Fn(CoefSET,x),
                   add = TRUE, n = NP)

The code then names the components of rawdt and converts it to a data.frame. Then follow up with the code:

    # make available data from fitted curve to user. Function returns it silently
    # but user can get data using simple assign '<-'
    invisible(rawdt)

But the user never gets access to rawdt since the invisible(rawdt) is not the last line in the function, rather the function returns NULL or the value of dev.cur() if save=TRUE.

**Comment by diegofcoelho** [comment]
fixed on 0.0.2.4
